Array Creation

In [1]:
import numpy as np
empty_arr = np.empty((2,2))
print(empty_arr)


[[0. 0.]
 [0. 0.]]


In [2]:
ones_arr = np.ones((4,2))
print(ones_arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [3]:
full_arr = np.full((3,3), 7)
print(full_arr)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
zeros_like = np.zeros_like(arr)
print(zeros_like)


[[0 0 0]
 [0 0 0]]


In [5]:
ones_like = np.ones_like(arr)
print(ones_like)


[[1 1 1]
 [1 1 1]]


In [6]:
new_list = [1,2,3,4]
np_array = np.array(new_list)
print(np_array)


[1 2 3 4]


array manipulation


In [7]:
arr = np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
matrix = np.arange(9).reshape(3,3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
identity = np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
rand_arr = np.random.random(30)
print(rand_arr.mean())


0.5417162185446077


In [11]:
rand_10x10 = np.random.random((10,10))
print(rand_10x10.min(), rand_10x10.max())


0.026155665840728592 0.9985883374002837


In [12]:
zero_arr = np.zeros(10)
zero_arr[4] = 1
print(zero_arr)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
arr_rev = np.array([1,2,0,0,4,0])[::-1]
print(arr_rev)


[0 4 0 0 2 1]


In [14]:
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print(border)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
checker = np.zeros((8,8), dtype=int)
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print(checker)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


arry operation

In [16]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
print(x+y)


[[ 6  8]
 [10 13]]


In [26]:
print(x-y)

[[-4 -4]
 [-4 -3]]


In [27]:
print(x*3)

[[ 3  6]
 [ 9 15]]


In [28]:
print(np.square(x))


[[ 1  4]
 [ 9 25]]


In [30]:
v = np.array([9,10])
w = np.array([11,12])
print(np.dot(v,w))


219


In [32]:
print(np.dot(x,v))


[29 77]


In [24]:
print(np.dot(x,y))


[[19 22]
 [50 58]]


In [25]:
print(np.concatenate((x,y), axis=0))
print(np.vstack((v,w)))


[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [33]:
try:
    print(np.concatenate((x,v)))
except ValueError as e:
    print("Error:", e)
    print("Reason: Shapes are incompatible (x is 2D, v is 1D).")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: Shapes are incompatible (x is 2D, v is 1D).


matrix operation

In [34]:
A = np.array([[3,4],[7,8]])
A_inv = np.linalg.inv(A)
print(np.dot(A, A_inv))


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [35]:
B = np.array([[5,3],[2,1]])
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))


AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [36]:
AB = np.dot(A,B)
print("(AB)^T:\n", AB.T)
print("B^T A^T:\n", np.dot(B.T, A.T))


(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [48]:
coeff = np.array([[3,1,-1],[2,-3,1],[1,-1,2]])
const = np.array([9,-1,-3])
solution_inv = np.dot(np.linalg.inv(coeff), const)
print(solution_inv)


[ 2.  1. -2.]


In [38]:
solution_solve = np.linalg.solve(coeff, const)
print(solution_solve)


[ 2.  1. -2.]


In [39]:
import time
list1 = list(range(1000000))
list2 = list(range(1000000))
start = time.time()
result_list = [a+b for a,b in zip(list1,list2)]
print("List addition time:", time.time()-start)


List addition time: 0.35561704635620117


In [40]:
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)
start = time.time()
result_np = arr1 + arr2
print("NumPy addition time:", time.time()-start)


NumPy addition time: 0.008534908294677734


In [41]:
start = time.time()
result_list = [a*b for a,b in zip(list1,list2)]
print("List multiplication time:", time.time()-start)


List multiplication time: 0.2734701633453369


In [42]:
start = time.time()
result_np = arr1 * arr2
print("NumPy multiplication time:", time.time()-start)


NumPy multiplication time: 0.023722171783447266


In [43]:
start = time.time()
dot_list = sum(a*b for a,b in zip(list1,list2))
print("List dot product time:", time.time()-start)


List dot product time: 0.18943095207214355


In [44]:
start = time.time()
dot_np = np.dot(arr1,arr2)
print("NumPy dot product time:", time.time()-start)


NumPy dot product time: 0.014410018920898438


In [46]:
import time 
listA = [[i for i in range(1000)] for _ in range(1000)]
listB = [[i for i in range(1000)] for _ in range(1000)]
start = time.time()
result = [[sum(a*b for a,b in zip(row,col)) for col in zip(*listB)] for row in listA]
print("List matrix multiplication time:", time.time()-start)


List matrix multiplication time: 198.70982599258423


In [47]:
arrA = np.array(listA)
arrB = np.array(listB)
start = time.time()
result_np = np.dot(arrA, arrB)
print("NumPy matrix multiplication time:", time.time()-start)


NumPy matrix multiplication time: 3.2927682399749756
